// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXNmuryDkSuAWIAeqRUAafkkShxygoW5A',
    appId: '1:345911525401:web:767d6ec45973eadf64aa88',
    messagingSenderId: '345911525401',
    projectId: 'flowdiagram-app',
    authDomain: 'flowdiagram-app.firebaseapp.com',
    storageBucket: 'flowdiagram-app.firebasestorage.app',
    measurementId: 'G-EK3H8TLLBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXn57bKp1ayq1QWtstRq_XBI7vY3-C1A8',
    appId: '1:345911525401:android:25d0c44346688f1964aa88',
    messagingSenderId: '345911525401',
    projectId: 'flowdiagram-app',
    storageBucket: 'flowdiagram-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3TPXcCpsQIFcerlusg3StU_foZWph_s0',
    appId: '1:345911525401:ios:c72ae8a4e23c6c9464aa88',
    messagingSenderId: '345911525401',
    projectId: 'flowdiagram-app',
    storageBucket: 'flowdiagram-app.firebasestorage.app',
    iosClientId: '345911525401-2th327d3sq2b255n1nkob4dfu6j4akqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flowdiagramapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3TPXcCpsQIFcerlusg3StU_foZWph_s0',
    appId: '1:345911525401:ios:c72ae8a4e23c6c9464aa88',
    messagingSenderId: '345911525401',
    projectId: 'flowdiagram-app',
    storageBucket: 'flowdiagram-app.firebasestorage.app',
    iosClientId: '345911525401-2th327d3sq2b255n1nkob4dfu6j4akqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flowdiagramapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXNmuryDkSuAWIAeqRUAafkkShxygoW5A',
    appId: '1:345911525401:web:96b467bc566a317364aa88',
    messagingSenderId: '345911525401',
    projectId: 'flowdiagram-app',
    authDomain: 'flowdiagram-app.firebaseapp.com',
    storageBucket: 'flowdiagram-app.firebasestorage.app',
    measurementId: 'G-7EQY4EYNDD',
  );
}
